// Catálogo Central da Biblioteca Didática ENEM - Destino 1000
import { LIVRO_MATEMATICA_FUNCOES } from './matematica-funcoes';
import { LIVRO_MATEMATICA_FUNDAMENTOS } from './matematica-fundamentos';
import { LIVRO_MATEMATICA_GEOMETRIA_ESPACIAL } from './matematica-geometria-espacial';
import { LIVRO_MATEMATICA_ESTATISTICA_PROBABILIDADE } from './matematica-estatistica-probabilidade';
import { LIVRO_MATEMATICA_GEOMETRIA_PLANA_TRIGONOMETRIA } from './matematica-geometria-plana-trigonometria';
import { LIVRO_MATEMATICA_COMBINATORIA_PROBABILIDADE } from './matematica-combinatoria-probabilidade';
import { LIVRO_MATEMATICA_ALGEBRA_MODELAGEM } from './matematica-algebra-modelagem';
import { LIVRO_NATUREZA_ELETRODINAMICA } from './natureza-eletrodinamica';
import { LIVRO_NATUREZA_ECOLOGIA } from './natureza-ecologia';
import { LIVRO_NATUREZA_QUIMICA_ORGANICA } from './natureza-quimica-organica';
import { LIVRO_NATUREZA_GENETICA_BIOTECNOLOGIA } from './natureza-genetica-biotecnologia';
import { LIVRO_NATUREZA_FISICO_QUIMICA } from './natureza-fisico-quimica';
import { LIVRO_NATUREZA_MECANICA_ENERGIA } from './natureza-mecanica-energia';
import { LIVRO_NATUREZA_ONDULATORIA_OPTICA } from './natureza-ondulatoria-optica';
import { LIVRO_NATUREZA_FISIOLOGIA_CITOLOGIA } from './natureza-fisiologia-citologia';
import { LIVRO_NATUREZA_BIOQUIMICA_CELULAR } from './natureza-bioquimica-celular';
import { LIVRO_NATUREZA_CINETICA_CATALISE } from './natureza-cinetica-catalise-bioenergetica';
import { LIVRO_NATUREZA_FISIOLOGIA_RENAL } from './natureza-fisiologia-renal-hemodinamica';
import { LIVRO_HUMANAS_BRASIL_CONTEMPORANEO } from './humanas-brasil-contemporaneo';
import { LIVRO_HUMANAS_FILOSOFIA_SOCIOLOGIA } from './humanas-filosofia-sociologia';
import { LIVRO_HUMANAS_GEOGRAFIA_GEOPOLITICA } from './humanas-geografia-geopolitica';
import { LIVRO_HUMANAS_HISTORIA_BRASIL } from './humanas-historia-brasil';
import { LIVRO_HUMANAS_AFRO_INDIGENA } from './humanas-afro-indigena';
import { LIVRO_HUMANAS_CIDADANIA_DIREITOS_HUMANOS } from './humanas-cidadania-direitos-humanos';
import { LIVRO_HUMANAS_FILOSOFIA_POLITICA_ESTADO } from './humanas-filosofia-politica-estado';
import { LIVRO_HUMANAS_ILUMINISMO_REVOLUCOES } from './humanas-iluminismo-revolucoes-burguesas';
import { LIVRO_HUMANAS_PRIMEIRA_REPUBLICA } from './humanas-primeira-republica-coronelismo-revoltas';
import { BOOK_LINGUAGENS_GENEROS_ARGUMENTACAO } from './linguagens-generos-argumentacao';
import { LIVRO_LINGUAGENS_LITERATURA_ARTES } from './linguagens-literatura-artes';
import { LIVRO_LINGUAGENS_GRAMATICA_VARIACAO } from './linguagens-gramatica-variacao';
import { LIVRO_LINGUAGENS_LINGUAS_ESTRANGEIRAS } from './linguagens-linguas-estrangeiras';
import { LIVRO_LINGUAGENS_TEORIA_LITERARIA } from './linguagens-teoria-literaria-poetica';
import { LIVRO_LINGUAGENS_ARGUMENTACAO_RETORICA } from './linguagens-argumentacao-discurso-retorica';
import { BOOK_REDACAO_MANUAL_NOTA_1000 } from './redacao-manual-nota-1000';

export const ALL_ENEM_BOOKS = [
  LIVRO_MATEMATICA_FUNCOES,
  LIVRO_MATEMATICA_FUNDAMENTOS,
  LIVRO_MATEMATICA_GEOMETRIA_ESPACIAL,
  LIVRO_MATEMATICA_ESTATISTICA_PROBABILIDADE,
  LIVRO_MATEMATICA_GEOMETRIA_PLANA_TRIGONOMETRIA,
  LIVRO_MATEMATICA_COMBINATORIA_PROBABILIDADE,
  LIVRO_MATEMATICA_ALGEBRA_MODELAGEM,
  LIVRO_NATUREZA_ELETRODINAMICA,
  LIVRO_NATUREZA_ECOLOGIA,
  LIVRO_NATUREZA_QUIMICA_ORGANICA,
  LIVRO_NATUREZA_GENETICA_BIOTECNOLOGIA,
  LIVRO_NATUREZA_FISICO_QUIMICA,
  LIVRO_NATUREZA_MECANICA_ENERGIA,
  LIVRO_NATUREZA_ONDULATORIA_OPTICA,
  LIVRO_NATUREZA_FISIOLOGIA_CITOLOGIA,
  LIVRO_NATUREZA_BIOQUIMICA_CELULAR,
  LIVRO_NATUREZA_CINETICA_CATALISE,
  LIVRO_NATUREZA_FISIOLOGIA_RENAL,
  LIVRO_HUMANAS_BRASIL_CONTEMPORANEO,
  LIVRO_HUMANAS_FILOSOFIA_SOCIOLOGIA,
  LIVRO_HUMANAS_GEOGRAFIA_GEOPOLITICA,
  LIVRO_HUMANAS_HISTORIA_BRASIL,
  LIVRO_HUMANAS_AFRO_INDIGENA,
  LIVRO_HUMANAS_CIDADANIA_DIREITOS_HUMANOS,
  LIVRO_HUMANAS_FILOSOFIA_POLITICA_ESTADO,
  LIVRO_HUMANAS_ILUMINISMO_REVOLUCOES,
  LIVRO_HUMANAS_PRIMEIRA_REPUBLICA,
  BOOK_LINGUAGENS_GENEROS_ARGUMENTACAO,
  LIVRO_LINGUAGENS_LITERATURA_ARTES,
  LIVRO_LINGUAGENS_GRAMATICA_VARIACAO,
  LIVRO_LINGUAGENS_LINGUAS_ESTRANGEIRAS,
  LIVRO_LINGUAGENS_TEORIA_LITERARIA,
  LIVRO_LINGUAGENS_ARGUMENTACAO_RETORICA,
  BOOK_REDACAO_MANUAL_NOTA_1000
];

export const BOOKS_BY_AREA = {
  matematica: [
    LIVRO_MATEMATICA_FUNCOES, 
    LIVRO_MATEMATICA_FUNDAMENTOS,
    LIVRO_MATEMATICA_GEOMETRIA_ESPACIAL,
    LIVRO_MATEMATICA_ESTATISTICA_PROBABILIDADE,
    LIVRO_MATEMATICA_GEOMETRIA_PLANA_TRIGONOMETRIA,
    LIVRO_MATEMATICA_COMBINATORIA_PROBABILIDADE,
    LIVRO_MATEMATICA_ALGEBRA_MODELAGEM
  ],
  natureza: [
    LIVRO_NATUREZA_ELETRODINAMICA, 
    LIVRO_NATUREZA_ECOLOGIA,
    LIVRO_NATUREZA_QUIMICA_ORGANICA,
    LIVRO_NATUREZA_GENETICA_BIOTECNOLOGIA,
    LIVRO_NATUREZA_FISICO_QUIMICA,
    LIVRO_NATUREZA_MECANICA_ENERGIA,
    LIVRO_NATUREZA_ONDULATORIA_OPTICA,
    LIVRO_NATUREZA_FISIOLOGIA_CITOLOGIA,
    LIVRO_NATUREZA_BIOQUIMICA_CELULAR,
    LIVRO_NATUREZA_CINETICA_CATALISE,
    LIVRO_NATUREZA_FISIOLOGIA_RENAL
  ],
  humanas: [
    LIVRO_HUMANAS_BRASIL_CONTEMPORANEO,
    LIVRO_HUMANAS_FILOSOFIA_SOCIOLOGIA,
    LIVRO_HUMANAS_GEOGRAFIA_GEOPOLITICA,
    LIVRO_HUMANAS_HISTORIA_BRASIL,
    LIVRO_HUMANAS_AFRO_INDIGENA,
    LIVRO_HUMANAS_CIDADANIA_DIREITOS_HUMANOS,
    LIVRO_HUMANAS_FILOSOFIA_POLITICA_ESTADO,
    LIVRO_HUMANAS_ILUMINISMO_REVOLUCOES,
    LIVRO_HUMANAS_PRIMEIRA_REPUBLICA
  ],
  linguagens: [
    BOOK_LINGUAGENS_GENEROS_ARGUMENTACAO,
    LIVRO_LINGUAGENS_LITERATURA_ARTES,
    LIVRO_LINGUAGENS_GRAMATICA_VARIACAO,
    LIVRO_LINGUAGENS_LINGUAS_ESTRANGEIRAS,
    LIVRO_LINGUAGENS_TEORIA_LITERARIA,
    LIVRO_LINGUAGENS_ARGUMENTACAO_RETORICA
  ],
  redacao: [BOOK_REDACAO_MANUAL_NOTA_1000]
};

export const getBookById = (id) => ALL_ENEM_BOOKS.find((b) => b.id === id) || null;

export const getChapter = (bookId, chapterId) => {
  const book = getBookById(bookId);
  if (!book) return null;
  const chapter = book.chapters.find((c) => c.id === chapterId || c.chapterNumber === chapterId);
  return chapter ? { book, chapter } : null;
};

